-- Assist Ride — hardening pass (round 18)
--
-- Three things the app has been trusting the client with. None of them is
-- exploitable by an ordinary user through the UI; all of them are trivially
-- exploitable by anyone who talks to the API directly with their own token.
--
-- 1. THE PICKUP PIN. It lived on ride_requests, which the matched driver can
--    read in full, so the driver's app could read the very number it was
--    meant to be checking — and the check itself ran on that device
--    (active-ride compared strings). Pins are now in their own table that
--    drivers cannot read, generated by the database rather than the client,
--    and verified by a function that performs the status change itself.
--    Five wrong attempts locks it: four digits is 10,000 guesses.
--
-- 2. RIDERS COULD SET ANY STATUS on their own ride with a direct UPDATE —
--    including 'completed' (dodging a late-cancellation fee) or 'no_show'
--    (blaming themselves, oddly, but also ending a ride a driver is on).
--    Riders may now only touch a ride that is still 'requested', and may not
--    change its status at all. Cancelling already goes through
--    rider_cancel_ride, which decides the fee (0016).
--
-- 3. RIDERS COULD READ THE WHOLE DRIVER ROW. "rider reads their matched
--    driver's profile" grants SELECT on driver_profiles, and RLS cannot
--    restrict columns — so licence number, date of birth and phone were
--    readable by any rider matched to that driver, even though the app only
--    ever asked for five fields. That policy is disabled and replaced by a
--    function returning just those fields.
--
-- NOT hardened, deliberately: the 45-second accept window. Since 0015 the
-- offer already widens by rank over time, and "expiry" is the driver's app
-- being polite and declining. Enforcing it server-side would need a job to
-- expire offers, which this project doesn't have — see SPEC.md §4.
--
-- Data note: this migration moves existing pins into the new table and then
-- clears ride_requests.pin. The column is left in place (vestigial) rather
-- than dropped.

-- ---------------------------------------------------------------------------
-- 1. Pins
-- ---------------------------------------------------------------------------
create table if not exists public.ride_pins (
  ride_id uuid primary key references public.ride_requests(id) on delete cascade,
  pin text not null,
  attempts int not null default 0,
  created_at timestamptz not null default now()
);

alter table public.ride_pins enable row level security;

-- Only the rider side sees the pin. Drivers get no policy at all: they
-- verify through start_ride_with_pin below, which never returns it.
create policy "rider side reads the ride pin" on public.ride_pins
  for select using (
    exists (
      select 1 from public.ride_requests rr
      where rr.id = ride_pins.ride_id
        and (rr.requested_by = auth.uid() or rr.rider_id = auth.uid())
    )
  );

-- Generated here, not by the client: a client-chosen pin is not a check.
create or replace function public.issue_ride_pin()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into ride_pins (ride_id, pin)
  values (new.id, lpad((floor(random() * 10000))::int::text, 4, '0'))
  on conflict (ride_id) do nothing;
  return null;
end;
$$;

create or replace trigger ride_requests_issue_pin
  after insert on public.ride_requests
  for each row execute function public.issue_ride_pin();

-- Existing rides keep working: move their pins across, then stop storing a
-- pin on the ride itself.
insert into public.ride_pins (ride_id, pin)
select id, pin from public.ride_requests where pin is not null
on conflict (ride_id) do nothing;

update public.ride_requests set pin = null where pin is not null;

-- The driver confirms the rider's pin and starts the ride in one step, so a
-- wrong pin cannot be skipped past by calling the status update directly.
create or replace function public.start_ride_with_pin(p_ride_id uuid, p_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  max_attempts constant int := 5;
  v_status text;
  v_driver uuid;
  v_pin text;
  v_attempts int;
begin
  select rr.status, rr.matched_driver_id, rp.pin, rp.attempts
    into v_status, v_driver, v_pin, v_attempts
  from ride_requests rr
  left join ride_pins rp on rp.ride_id = rr.id
  where rr.id = p_ride_id
  for update of rr;

  if not found or v_driver is distinct from auth.uid() then
    raise exception 'only the matched driver can start this ride' using errcode = '42501';
  end if;

  if v_status <> 'arrived' then
    raise exception 'the ride must be at pickup to start (status: %)', v_status using errcode = '55000';
  end if;

  if v_pin is null then
    raise exception 'this ride has no pin on file' using errcode = '55000';
  end if;

  if v_attempts >= max_attempts then
    raise exception 'too many incorrect pin attempts — contact support' using errcode = '55000';
  end if;

  if p_pin is distinct from v_pin then
    update ride_pins set attempts = attempts + 1 where ride_id = p_ride_id;
    raise exception 'that pin does not match' using errcode = '22023';
  end if;

  update ride_requests set status = 'in_progress', updated_at = now() where id = p_ride_id;
  return jsonb_build_object('started', true);
end;
$$;

revoke execute on function public.start_ride_with_pin(uuid, text) from public, anon;
grant execute on function public.start_ride_with_pin(uuid, text) to authenticated;

-- A pin check is only a check if it's the only way past it. Without this a
-- driver could call the ordinary status update (arrived -> in_progress) and
-- never enter a pin at all. start_ride_with_pin is SECURITY DEFINER, so it
-- still sets the status itself.
alter policy "driver claims a requested ride" on public.ride_requests
  with check (matched_driver_id = auth.uid() and status <> 'in_progress');

-- ---------------------------------------------------------------------------
-- 2. Riders can no longer set statuses by hand
-- ---------------------------------------------------------------------------
-- Still enough for rescheduling a searching ride (0011), which only touches
-- ride_mode and requested_time. Cancelling goes through rider_cancel_ride,
-- which is SECURITY DEFINER and unaffected by this.
alter policy "rider updates own ride requests" on public.ride_requests
  using (
    status = 'requested'
    and (requested_by = auth.uid() or rider_id = auth.uid())
  )
  with check (
    status = 'requested'
    and (requested_by = auth.uid() or rider_id = auth.uid())
  );

-- ---------------------------------------------------------------------------
-- 3. Riders see only the driver fields the app actually shows
-- ---------------------------------------------------------------------------
create or replace function public.matched_driver_public(p_ride_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public
stable
as $$
declare
  v_driver uuid;
  v_row record;
begin
  select rr.matched_driver_id into v_driver
  from ride_requests rr
  where rr.id = p_ride_id
    and (rr.requested_by = auth.uid() or rr.rider_id = auth.uid());

  if not found then
    raise exception 'that is not your ride' using errcode = '42501';
  end if;

  if v_driver is null then
    return null; -- no driver matched yet
  end if;

  select full_name, vehicle, plate, ramp_equipped, capability_tags
    into v_row
  from driver_profiles where id = v_driver;

  return jsonb_build_object(
    'full_name', v_row.full_name,
    'vehicle', v_row.vehicle,
    'plate', v_row.plate,
    'ramp_equipped', v_row.ramp_equipped,
    'capability_tags', to_jsonb(v_row.capability_tags)
  );
end;
$$;

revoke execute on function public.matched_driver_public(uuid) from public, anon;
grant execute on function public.matched_driver_public(uuid) to authenticated;

-- Disabled rather than dropped, so it's obvious what happened and easy to
-- restore if this turns out to be wrong. RLS cannot restrict columns, so
-- there is no version of this policy that exposes only the public fields.
alter policy "rider reads their matched driver's profile" on public.driver_profiles
  using (false);
